In [1]:
import numpy as np
from scipy.optimize import linprog

In [2]:
def boolean_functions(n):
    input_combinations = 2 ** n
    num_functions = 2 ** input_combinations
    functions = np.array([np.array(list(np.binary_repr(i, width=input_combinations)), dtype=int) 
                          for i in range(num_functions)]) 
    return functions

In [3]:
for n in range(1, 5):
    print(f"\nBoolean functions for n = {n}:")
    functions = boolean_functions(n)
    print(functions)
    print(f"Total functions: {functions.shape[0]}")


Boolean functions for n = 1:
[[0 0]
 [0 1]
 [1 0]
 [1 1]]
Total functions: 4

Boolean functions for n = 2:
[[0 0 0 0]
 [0 0 0 1]
 [0 0 1 0]
 [0 0 1 1]
 [0 1 0 0]
 [0 1 0 1]
 [0 1 1 0]
 [0 1 1 1]
 [1 0 0 0]
 [1 0 0 1]
 [1 0 1 0]
 [1 0 1 1]
 [1 1 0 0]
 [1 1 0 1]
 [1 1 1 0]
 [1 1 1 1]]
Total functions: 16

Boolean functions for n = 3:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 1 0]
 ...
 [1 1 1 ... 1 0 1]
 [1 1 1 ... 1 1 0]
 [1 1 1 ... 1 1 1]]
Total functions: 256

Boolean functions for n = 4:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 1 0]
 ...
 [1 1 1 ... 1 0 1]
 [1 1 1 ... 1 1 0]
 [1 1 1 ... 1 1 1]]
Total functions: 65536


In [4]:
functions = boolean_functions(3)
print(functions[255])

[1 1 1 1 1 1 1 1]


In [5]:
functions = boolean_functions(4)
print(functions[255])

[0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1]


In [6]:
def generate_boolean_functions(n):
    num_functions = 2 ** (2 ** n)
    functions = []
    for i in range(num_functions):
        func = np.zeros((2 ** n,), dtype=bool)
        for j in range(2 ** n):
            func[j] = (i >> j) & 1
        functions.append(func)
    return functions

In [ ]:
for n in range(1, 5):
    print(f"Boolean functions for {n} inputs:")
    functions = generate_boolean_functions(n)
    for i, func in enumerate(functions):
        print(f"Function {i+1}: {func}")
    print()

Boolean functions for 1 inputs:
Function 1: [False False]
Function 2: [ True False]
Function 3: [False  True]
Function 4: [ True  True]

Boolean functions for 2 inputs:
Function 1: [False False False False]
Function 2: [ True False False False]
Function 3: [False  True False False]
Function 4: [ True  True False False]
Function 5: [False False  True False]
Function 6: [ True False  True False]
Function 7: [False  True  True False]
Function 8: [ True  True  True False]
Function 9: [False False False  True]
Function 10: [ True False False  True]
Function 11: [False  True False  True]
Function 12: [ True  True False  True]
Function 13: [False False  True  True]
Function 14: [ True False  True  True]
Function 15: [False  True  True  True]
Function 16: [ True  True  True  True]

Boolean functions for 3 inputs:
Function 1: [False False False False False False False False]
Function 2: [ True False False False False False False False]
Function 3: [False  True False False False False False Fals

Function 1: [False False False False False False False False False False False False
 False False False False]
Function 2: [ True False False False False False False False False False False False
 False False False False]
Function 3: [False  True False False False False False False False False False False
 False False False False]
Function 4: [ True  True False False False False False False False False False False
 False False False False]
Function 5: [False False  True False False False False False False False False False
 False False False False]
Function 6: [ True False  True False False False False False False False False False
 False False False False]
Function 7: [False  True  True False False False False False False False False False
 False False False False]
Function 8: [ True  True  True False False False False False False False False False
 False False False False]
Function 9: [False False False  True False False False False False False False False
 False False False False]
F

Function 639: [False  True  True  True  True  True  True False False  True False False
 False False False False]
Function 640: [ True  True  True  True  True  True  True False False  True False False
 False False False False]
Function 641: [False False False False False False False  True False  True False False
 False False False False]
Function 642: [ True False False False False False False  True False  True False False
 False False False False]
Function 643: [False  True False False False False False  True False  True False False
 False False False False]
Function 644: [ True  True False False False False False  True False  True False False
 False False False False]
Function 645: [False False  True False False False False  True False  True False False
 False False False False]
Function 646: [ True False  True False False False False  True False  True False False
 False False False False]
Function 647: [False  True  True False False False False  True False  True False False
 False Fa

Function 1002: [ True False False  True False  True  True  True  True  True False False
 False False False False]
Function 1003: [False  True False  True False  True  True  True  True  True False False
 False False False False]
Function 1004: [ True  True False  True False  True  True  True  True  True False False
 False False False False]
Function 1005: [False False  True  True False  True  True  True  True  True False False
 False False False False]
Function 1006: [ True False  True  True False  True  True  True  True  True False False
 False False False False]
Function 1007: [False  True  True  True False  True  True  True  True  True False False
 False False False False]
Function 1008: [ True  True  True  True False  True  True  True  True  True False False
 False False False False]
Function 1009: [False False False False  True  True  True  True  True  True False False
 False False False False]
Function 1010: [ True False False False  True  True  True  True  True  True False False


Function 1593: [False False False  True  True  True False False False  True  True False
 False False False False]
Function 1594: [ True False False  True  True  True False False False  True  True False
 False False False False]
Function 1595: [False  True False  True  True  True False False False  True  True False
 False False False False]
Function 1596: [ True  True False  True  True  True False False False  True  True False
 False False False False]
Function 1597: [False False  True  True  True  True False False False  True  True False
 False False False False]
Function 1598: [ True False  True  True  True  True False False False  True  True False
 False False False False]
Function 1599: [False  True  True  True  True  True False False False  True  True False
 False False False False]
Function 1600: [ True  True  True  True  True  True False False False  True  True False
 False False False False]
Function 1601: [False False False False False False  True False False  True  True False


Function 2264: [ True  True  True False  True False  True  True False False False  True
 False False False False]
Function 2265: [False False False  True  True False  True  True False False False  True
 False False False False]
Function 2266: [ True False False  True  True False  True  True False False False  True
 False False False False]
Function 2267: [False  True False  True  True False  True  True False False False  True
 False False False False]
Function 2268: [ True  True False  True  True False  True  True False False False  True
 False False False False]
Function 2269: [False False  True  True  True False  True  True False False False  True
 False False False False]
Function 2270: [ True False  True  True  True False  True  True False False False  True
 False False False False]
Function 2271: [False  True  True  True  True False  True  True False False False  True
 False False False False]
Function 2272: [ True  True  True  True  True False  True  True False False False  True


Function 2859: [False  True False  True False  True False False  True  True False  True
 False False False False]
Function 2860: [ True  True False  True False  True False False  True  True False  True
 False False False False]
Function 2861: [False False  True  True False  True False False  True  True False  True
 False False False False]
Function 2862: [ True False  True  True False  True False False  True  True False  True
 False False False False]
Function 2863: [False  True  True  True False  True False False  True  True False  True
 False False False False]
Function 2864: [ True  True  True  True False  True False False  True  True False  True
 False False False False]
Function 2865: [False False False False  True  True False False  True  True False  True
 False False False False]
Function 2866: [ True False False False  True  True False False  True  True False  True
 False False False False]
Function 2867: [False  True False False  True  True False False  True  True False  True


Function 3459: [False  True False False False False False  True  True False  True  True
 False False False False]
Function 3460: [ True  True False False False False False  True  True False  True  True
 False False False False]
Function 3461: [False False  True False False False False  True  True False  True  True
 False False False False]
Function 3462: [ True False  True False False False False  True  True False  True  True
 False False False False]
Function 3463: [False  True  True False False False False  True  True False  True  True
 False False False False]
Function 3464: [ True  True  True False False False False  True  True False  True  True
 False False False False]
Function 3465: [False False False  True False False False  True  True False  True  True
 False False False False]
Function 3466: [ True False False  True False False False  True  True False  True  True
 False False False False]
Function 3467: [False  True False  True False False False  True  True False  True  True


Function 3925: [False False  True False  True False  True False  True  True  True  True
 False False False False]
Function 3926: [ True False  True False  True False  True False  True  True  True  True
 False False False False]
Function 3927: [False  True  True False  True False  True False  True  True  True  True
 False False False False]
Function 3928: [ True  True  True False  True False  True False  True  True  True  True
 False False False False]
Function 3929: [False False False  True  True False  True False  True  True  True  True
 False False False False]
Function 3930: [ True False False  True  True False  True False  True  True  True  True
 False False False False]
Function 3931: [False  True False  True  True False  True False  True  True  True  True
 False False False False]
Function 3932: [ True  True False  True  True False  True False  True  True  True  True
 False False False False]
Function 3933: [False False  True  True  True False  True False  True  True  True  True
